listlevel = ["",
             "",
             '',
             '',
             '                                                  hh',
             '                          tttttt               tttttt',
             '                                                                                hhhh',
             '                                               tttttt               ttttttttttttttttttttttttttt',
             '                  ttttt',
             't                                              tttttt',
             '',
             't                                              tttttt',
             't',
             't                                 ttttt',
             '                   ',
             't                  ',
             't                  ', 
             't                                         ttttttt',
             't             ',
             't',
             't                                                      tttttrrrrtttttttt',
             't',
             't                                                                       p     p     tttttrrrrrttt',
             't                                 p         p        p       rrrrrrr',
             'ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt']

width,height = 620, 360