listlevel = ["",
             "",
             '',
             '',
             '                                                  hh',
             '                          tttttt               tttttt',
             '                                                                                hhhh',
             '                                               tttttt               ttttttttttttttttttttttttttt',
             '                  ttttt',
             '',
             '',
             '',
             '                                 ttttt',
             '                   ',
             '                  ',
             '                  ', 
             '                                         ttttttt',
             '             ',
             '',
             '                                                      tttttrrrrtttttttt',
             '',
             '                                                                                 tttttrrrrrttt',
             '                                                         rrrrrrr',
             'ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt']

width,height = 620, 360