listlevel = ["",
             "",
             '',
             '',
             '',
             'tttttt               tttttt',
             '',
             '                                                         ttttttttttttttttttttttttttt',
             'ttttt',
             '',
             '',
             '',
             '            ttttt',
             '                   ',
             '                  ',
             '                  ', 
             '                 ttttttt',
             '             ',
             '',
             'tttttttttttttttt',
             '',
             '',
             '',
             'tttrrttttttttttttt rrrrrrttttttttttttttttttt']

width,height = 620, 360